version: '3.8'

services:
  app:
    image: php:8.1-apache
    container_name: lorekeeper_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=lorekeeper
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - lorekeeper_network

  db:
    image: mysql:5.7
    container_name: lorekeeper_db
    restart: always
    environment:
      MYSQL_DATABASE: lorekeeper
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - lorekeeper_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lorekeeper_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - lorekeeper_network

networks:
  lorekeeper_network:
    driver: bridge

volumes:
  db_data:
